runtime: custom
env: flex

# Environment variables (optional)
env_variables:
  PROJECT_ID: your-project-id

# Handlers define the URL patterns to handle
handlers:
  - url: /.*
    script: auto
    secure: always
