steps:
  # Step 2: Build the Docker container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/helloworld", "."]

  # Step 3: Push the container image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/helloworld"]

  # Step 4: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["app", "deploy"]

# Specify a timeout for the build process
timeout: "1600s"

# Optionally, set substitutions for variables
substitutions:
  _PROJECT_ID: "your-project-id"
